# Generated by Django 3.2.9 on 2022-03-14 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models
import ys_x_ray.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XRayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_xray', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_xray', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequsetXRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('request', models.BooleanField(default=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('confirm_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('discharge', models.BooleanField(default=False)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('reject', models.BooleanField(default=False)),
                ('reject_date', models.DateField(blank=True, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(blank=True, choices=[('patient', 'patient'), ('staff', 'staff')], max_length=7, null=True)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('disabled_date', models.DateField(blank=True, null=True)),
                ('expire_days', models.PositiveIntegerField(default=7)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('result', models.FileField(blank=True, null=True, storage=user.models.OverwriteStorage(), upload_to=ys_x_ray.models.xray_upload)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_doctor', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_xray', to='ys_x_ray.xraymodel')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_patient', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
