# Generated by Django 3.2.9 on 2022-03-14 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ys_appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('number_of_units', models.IntegerField()),
                ('unit', models.CharField(blank=True, choices=[('Tab', 'Tab'), ('ml', 'ml')], max_length=50, null=True)),
                ('number_of_times', models.PositiveIntegerField()),
                ('time', models.CharField(blank=True, choices=[('After', 'After'), ('Before', 'Before')], max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category', models.CharField(blank=True, choices=[('cold', 'cold'), ('headech', 'headech'), ('painkiller', 'painkiller')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('appoint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ys_appointment.requsetappointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_prescription', to=settings.AUTH_USER_MODEL)),
                ('medicines', models.ManyToManyField(blank=True, to='ys_pharmacy.Medicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_prescription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('request', models.BooleanField(default=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('confirm_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('discharge', models.BooleanField(default=False)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('reject', models.BooleanField(default=False)),
                ('reject_date', models.DateField(blank=True, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(blank=True, choices=[('patient', 'patient'), ('staff', 'staff')], max_length=7, null=True)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('disabled_date', models.DateField(blank=True, null=True)),
                ('expire_days', models.PositiveIntegerField(default=7)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_doctor', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_prescription', to='ys_pharmacy.prescription')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_patient', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
