# Generated by Django 3.2.9 on 2022-03-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ys_appointment', '0001_initial'),
        ('ys_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmodel',
            name='appoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ys_appointment.requsetappointment'),
        ),
        migrations.AlterField(
            model_name='requestlab',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestlab',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestlab',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
