# Generated by Django 4.0.2 on 2022-02-24 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[user.models.validate_name], verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='UserVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(default=0)),
                ('blood_pressure_up', models.IntegerField(default=0)),
                ('blood_pressure_down', models.IntegerField(default=0)),
                ('respiration_rate', models.IntegerField(default=0)),
                ('temprature', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=7)),
                ('avatar', models.ImageField(default='profile/avatar.png', storage=user.models.OverwriteStorage(), upload_to=user.models.image_upload)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], max_length=8, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
