# Generated by Django 3.2.9 on 2022-03-14 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(blank=True, choices=[('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('None', 'None'), ('HR', 'HR'), ('Dr', 'Dr'), ('Nurse', 'Nurse'), ('pharmacist', 'pharmacist'), ('Secretary', 'Secretary')], default='None', max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('degree', models.CharField(choices=[('None', 'None'), ('PH', 'PH'), ('colleague', 'colleague'), ('Master', 'Master'), ('Graduated', 'Graduated')], default='None', max_length=20)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobprofile', to=settings.AUTH_USER_MODEL)),
                ('work_days', models.ManyToManyField(blank=True, to='xstaff.JobDays')),
            ],
        ),
    ]
